#!/bin/bash

read -p "Remove this project entirely? (incl. volumes) (y/n)? " CONT
if [ "$CONT" = "y" ]; then
  ddev delete -Oy
  docker volume rm fluid-page-cache-v10-data fluid-page-cache-v11-data
else
  echo "Canceled.";
fi
